apiVersion: v1 # Versi API Kubernetes yang digunakan
kind: Secret # Jenis objek Kubernetes yang akan dibuat (Secret)
metadata:
  name: mongo-secret # Nama untuk Secret yang akan dibuat
data:
  MONGO_ROOT_USERNAME: YWRtaW4= # Data terenkripsi bentuk base64 untuk nama pengguna root MongoDB (admin)
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # Data terenkripsi bentuk base64 untuk kata sandi root MongoDB (supersecretpassword)
