apiVersion: v1 # Versi API Kubernetes yang digunakan
kind: Service # Jenis objek Kubernetes yang akan dibuat (Service)
metadata:
  name: karsajobs-ui # Nama untuk Service yang akan dibuat
spec:
  type: NodePort # Jenis Service yang digunakan (NodePort)
  selector: # Selektor yang digunakan untuk menentukan pod yang akan dijadikan target oleh Service
    app: karsajobs-ui # Menargetkan (query) pod yang memiliki label  'app: karsajobs-ui'
  ports:
    - port: 8000 # Port yang akan di-expose oleh Service
      targetPort: 8000 # Port pada pod yang akan ditargetkan oleh Service
      nodePort: 30097 # Port yang digunakan oleh node karena menggunakan 'type: NodePort'
